prompt Creating sample objects for the Auth0 + ORDS + ADB demo

-- This script prepares a minimal table and sample rows for the secured GET
-- endpoint.
--
-- It enables the current schema for ORDS only when the schema is not already
-- enabled. If your schema is already ORDS-enabled, this script preserves the
-- existing base path and you should set ORDS_SCHEMA in .env to match that
-- existing pattern.

declare
  l_is_enabled number;
begin
  select count(*)
    into l_is_enabled
    from user_ords_schemas
   where parsing_schema = user
     and status = 'ENABLED';

  if l_is_enabled = 0 then
    ords.enable_schema(
      p_enabled             => true,
      p_schema              => user,
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'demo',
      p_auto_rest_auth      => false
    );
  end if;

  commit;
end;
/

begin
  execute immediate q'[
    create table demo_secure_messages (
      id         number generated by default on null as identity primary key,
      message    varchar2(200 char) not null,
      created_at timestamp with time zone default systimestamp not null
    )
  ]';
exception
  when others then
    if sqlcode = -955 then
      null;
    else
      raise;
    end if;
end;
/

merge into demo_secure_messages target
using (
  select 1 as id, 'Auth0 + ORDS demo is reachable.' as message from dual
  union all
  select 2 as id, 'This endpoint is intended to be protected by an ORDS privilege.' as message from dual
) source
on (target.id = source.id)
when matched then
  update set target.message = source.message
when not matched then
  insert (id, message)
  values (source.id, source.message);

commit;
